name: Tests

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Dependencies
        run: |
          pip install --user poetry && poetry install
      - name: Run
        run: poetry run pytest
